parser: '@typescript-eslint/parser'
extends:
  - 'eslint:recommended'
  - 'plugin:@typescript-eslint/recommended'
  - 'plugin:@typescript-eslint/recommended-requiring-type-checking'
parserOptions:
  ecmaVersion: 2020
  sourceType: 'module'
  # tsconfigRootDir: __dirname
  project:
    - './tsconfig.json'
    - './tsconfig.node.json'
env:
  es6: true
  browser: true
plugins:
  - '@typescript-eslint/eslint-plugin'
ignorePatterns:
  - 'node_modules'
